### ISSUE TITLE
Could you please upload or send me some instance ？

### ISSUE THREAD

**Issue by wjpamz** [AntoinePassemiers/P-Center-Problem#1]
Hello, I am a newcomer to programming. I tried it for a few days and wanted to make a data file to run, but it failed. Can you upload or send me some instance? thank you very much!
My email address is bvcx333333@gmail.com

**Comment by AntoinePassemiers** [comment]
Hello, no worries I was also new to Julia when I wrote this code. I just uploaded some easy and hard instances so you can properly test it. Let me know if you get some more issues :D
